package servent.message;

public enum MessageType {
	HELLO_TO_BOOTSTRAP, HELLO_FROM_BOOTSTRAP, HELLO_TO_NODE, HELLO_FROM_NODE,
	TOKEN, REQUEST_TOKEN, FIRST_REQUEST, GOT_REQUEST,
	UPDATE_SYSTEM, SYSTEM_UPDATED,
	PULL_FILE, SEND_FILE,
	PING, PONG
}
