package servent.message;

public enum MessageType {
	HELLO_TO_BOOTSTRAP, HELLO_FROM_BOOTSTRAP, HELLO_TO_NODE, HELLO_FROM_NODE, NEW_NODE_TO_BOOTSTRAP, REMOVE_NODE_TO_BOOTSTRAP,
	TOKEN, REQUEST_TOKEN, FIRST_REQUEST, GOT_REQUEST,
	UPDATE_SYSTEM, SYSTEM_UPDATED,
	PULL_FILE, SEND_FILE,
	PING, PONG, IS_HE_OK, ARE_YOU_OK, NOT_OK, OK, HE_IS_OK
}
